Added usage info

diff --git a/fluxgen b/fluxgen
--- a/fluxgen
+++ b/fluxgen
@@ -1,32 +1,43 @@
 #!/bin/bash
 
-while getopts 'n:r:u:p:b:l:' opt; do 
-case ${opt} in
-  n )
-    export NAMESPACE=$OPTARG
-    ;;
-  r )
-    export GIT_REPO=$OPTARG
-    ;;
-  u )
-    export GIT_USER=$OPTARG
-    ;;
-  p )
-    export GIT_PASS=$OPTARG
-    ;;
-  b )
-    export GIT_BRANCH=$OPTARG
-    ;;
-  l )
-    export GIT_PATH=$OPTARG
-    ;;
-  \? )
-    echo "Invalid option: $OPTARG" 1>&2
-    ;;
-  : )
-    echo "Invalid option: $OPTARG requires an argument" 1>&2
-    ;;
-esac
+usage() {
+  echo "usage: $(basename $0) -n namespace -r repository -u git-user -p git-password -b git-branch -d git-path"
+  exit 1
+}
+
+if (( $# == 0 )); then
+  usage
+fi
+
+while getopts ':n:r:u:p:b:l:' opt; do 
+  case ${opt} in
+    n )
+      export NAMESPACE=$OPTARG
+      ;;
+    r )
+      export GIT_REPO=$OPTARG
+      ;;
+    u )
+      export GIT_USER=$OPTARG
+      ;;
+    p )
+      export GIT_PASS=$OPTARG
+      ;;
+    b )
+      export GIT_BRANCH=$OPTARG
+      ;;
+    d )
+      export GIT_PATH=$OPTARG
+      ;;
+    \? )
+      echo "Invalid option: $OPTARG" 1>&2
+      exit 1
+      ;;
+    : )
+      echo "Invalid option: $OPTARG requires an argument" 1>&2
+      exit 1
+      ;;
+  esac
 done
 
 cat k8s/*.yaml | envsubst
